### ISSUE TITLE
对原有程序进行逆向可能性的探讨

### ISSUE THREAD

**Issue by xiaofengorz** [futz12/HackGowild#1]
机器中模型控制的相关程序可否提取出来？是否有可能逆向服务器与控制程序的交互逻辑等，以达到最大程度还原原有功能的目的？谢谢。

**Comment by xiaofengorz** [comment]
抱歉，没有看到已有的信息，疑问已解决。md文件中的研究群已无法检索，不知道有没有新的群。

**Comment by futz12** [comment]
143858000
